language: node_js

node_js:
 - "0.10"

before_install:
 # we need c++11 compatible g++
 - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
 - sudo apt-get -y update
 - sudo apt-get -y install gcc-4.7 g++-4.7
 # first test install of binary
 - npm install --verbose
 - make test

install:
 # next test source compile, so get dependencies
 - sudo apt-add-repository --yes ppa:mapnik/boost
 - sudo apt-get -y update -qq
 - sudo apt-get -y install git build-essential libboost-dev zlib1g-dev protobuf-compiler libprotobuf-lite7 libprotobuf-dev libexpat1-dev libsparsehash-dev
 - git clone https://github.com/scrosby/OSM-binary.git
 - cd OSM-binary/src
 - make && sudo make install
 - cd ../../

before_script:
 - git clone https://github.com/osmcode/libosmium.git ../libosmium
 - CXX=g++-4.7 npm install

script:
 - make test
